INTERESTS = [
    ['Photography'],
    ['Sculpture'],
    ['Home', 'Garden'],
    ['Animals'],
    ['Charity'],
    ['Law'],
    ['Military'],
    ['Politics'],
    ['Religion'],
    ['Travel'],
    ['Vehicles'],
    ['Shopping', 'Fashion'],
    ['Outdoor recreation'],
    ['Sports'],
    ['Fitness', 'meditation'],
    ['Technology'],
    ['News'],
    ['Painting'],
    ['Architecture', 'Design'],
    ['Books'],
    ['Business', 'Economy'],
    ['RealEstate', 'Construction'],
    ['Dance'],
    ['Engineering'],
    ['Family', 'Relationships'],
    ['Food', 'drink'],
    ['Games'],
    ['HealthCare'],
    ['Live Events'],
    ['Movies'],
    ['Science', 'HigherEducation'],
    ['TV'],
    ['Entrepreneurship']
]

